# @package _global_
dataset_name: ACCpatterns_LARGE_CINGULATE_RIGHT
data_dir: ${dataset_folder}/ACCpatterns/crops/2mm/LARGE_CINGULATE./mask/Rskeleton.npy
subject_dir: ${dataset_folder}/ACCpatterns/crops/2mm/LARGE_CINGULATE./mask/Rskeleton_subject.csv
in_shape: [1, 18, 73, 57]
subjects_to_remove: ''
remove_subjects: False