# @package _global_
dataset_name: FIP_right_HCP
data_dir: ${dataset_folder}/hcp/crops/2mm/F.I.P./mask/Rskeleton.npy
subject_dir: ${dataset_folder}/hcp/crops/2mm/F.I.P./mask/Rskeleton_subject.csv
in_shape: [1, 39, 45, 44]
subjects_to_remove: ''
remove_subjects: False