# @package _global_
dataset_name: SC-sylv_left_HCP
data_dir: "/neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/S.C.-sylv./mask/Lskeleton.pkl"
subject_dir: "/neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/S.C.-sylv./mask/Lskeleton_subject.csv"
in_shape: [1, 38, 36, 49]
subjects_to_remove: None
remove_subjects: False