# @package _global_
dataset_name: SC-sylv_right_subset_UKB
data_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Rskeleton.npy
subject_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Rskeleton_subject.csv
in_shape: [1, 42, 34, 49]
subjects_to_remove: /neurospin/tmp/cmendoza/UKB_processing/2mm/S.C.-sylv./Subs_to_remove_sulci_train.csv
remove_subjects: True