# @package _global_
dataset_name: SOr_left_HCP
data_dir: ${dataset_folder}/hcp/crops/2mm/S.Or./mask/Lskeleton.npy
subject_dir: ${dataset_folder}/hcp/crops/2mm/S.Or./mask/Lskeleton_subject.csv
in_shape: [1, 30, 38, 22]
subjects_to_remove: ''
remove_subjects: False