# @package _global_
dataset_name: UKB_S.F.int.-F.C.M.ant._right_Comm_Overconnectivity
in_shape: [1, 33, 113, 107]
Train_list: ${dataset_folder}/DataSplit_DL/train.tsv
Rcon_val_list: ${dataset_folder}/DataSplit_DL/val_rconerror.tsv
Class_val_list: ${dataset_folder}/DataSplit_DL/val_anorm.tsv
Anomaly: Overconnectivity
Criteria: Comm
Region: S.F.int.-F.C.M.ant._right
Database: UKB
path_crops: ${dataset_folder}/crops/S.F.int.-F.C.M.ant._right/Comm
path_anom: ${dataset_folder}/FakeAnomaly_crops/UKB/S.F.int.-F.C.M.ant._right/Comm/Overconnectivity
minl: 0
maxl: 250
referential: icbm09c
