# @package _global_
dataset_name: UKB_S.T.s._left_Comm_Underconnectivity
data_dir: null
subject_dir: null
in_shape: [1, 49, 109, 99]
Train_list: ${dataset_folder}/DataSplit_DL/train.tsv
Rcon_val_list: ${dataset_folder}/DataSplit_DL/val_rconerror.tsv
Class_val_list: ${dataset_folder}/DataSplit_DL/val_anorm.tsv
Anomaly: Underconnectivity
Criteria: Comm
Region: S.T.s._left
Database: UKB
path_crops: ${dataset_folder}/crops/S.T.s._left/Comm
path_anom: ${dataset_folder}/FakeAnomaly_crops/UKB/S.T.s._left/Comm/Underconnectivity
minl: 0
maxl: 250
referential: icbm09c
