# @package _global_
dataset_name: UKB_S.T.s._right_SWM_Overconnectivity
data_dir: null
subject_dir: null
in_shape: [1, 47, 103, 101]
Train_list: ${dataset_folder}/DataSplit_DL/train.tsv
Rcon_val_list: ${dataset_folder}/DataSplit_DL/val_rconerror.tsv
Class_val_list: ${dataset_folder}/DataSplit_DL/val_anorm.tsv
Anomaly: Overconnectivity
Criteria: SWM
Region: S.T.s._right
Database: UKB
path_crops: ${dataset_folder}/crops/S.T.s._right/SWM
path_anom: ${dataset_folder}/FakeAnomaly_crops/UKB/S.T.s._right/SWM/Overconnectivity
minl: 0
maxl: 80
referential: icbm09c
