# @package _global_
dataset_name: UKB_S.C.-sylv._right_SWM
in_shape: [1, 83, 67, 97]
Train_list: ${dataset_folder}/DataSplit_DL/train.tsv
Rcon_val_list: ${dataset_folder}/DataSplit_DL/val_rconerror.tsv
Class_val_list: ${dataset_folder}/DataSplit_DL/val_anorm.tsv
Anomaly: None
Criteria: SWM
Region: S.C.-sylv._right
Database: UKB
path_crops: ${dataset_folder}/crops/S.C.-sylv._right/SWM
path_anom: ${dataset_folder}/FakeAnomaly_crops/UKB/S.C.-sylv._right/SWM/None
path_stats: ${dataset_folder}/Stats_Anomaly/UKB/UKB_S.C.-sylv._right_None_SWM.pkl
minl: 0
maxl: 80
referential: icbm09c
