# @package _global_
dataset_name: UKB_S.C.-sylv._right_Comm
in_shape: [1, 83, 67, 97]
Train_list: ${dataset_folder}/DataSplit_DL/train.tsv
Rcon_val_list: ${dataset_folder}/DataSplit_DL/val_rconerror.tsv
Class_val_list: null
Anomaly: null
Criteria: Comm
Region: S.C.-sylv._right
Database: UKB
path_crops: ${dataset_folder}/crops/S.C.-sylv._right/Comm
path_anom: null
minl: 0
maxl: 250
referential: icbm09c
